services:
  php:
    build: ./docker
    container_name: php
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql

  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  mysql:
    image: mysql:9.5
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
      MYSQL_PASSWORD: root
      LC_ALL: C.UTF-8
    volumes:
      - ./docker/mysql:/etc/mysql/conf.d:ro,delegated
      - blog:/var/lib/mysql:delegated
    networks:
      - default
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 100000000
    ports:
      - "127.0.0.1:8080:80"

  node:
      image: node:latest
      container_name: node
      working_dir: /home/node
      user: node
      command: bash -c "npm run dev"
      volumes:
          - ./:/home/node:delegated

networks:
  default:
    driver: bridge

volumes:
  blog:
